### ISSUE TITLE
v1.15 ready?

### ISSUE THREAD

**Issue by raymatos** [philbertphotos/osticket-bootstrap-theme#25]
ready for osticket version 1.15

**Comment by pvi-github** [comment]
Hello,

Does this mean that it's already ready for 1.15 or that ti is not ?

And if it's not is there a plan to ?

Thanks for all the good work @philbertphotos  !

**Comment by philbertphotos** [comment]
Should work as is but will be going through it with a find tooth comb to check for incompatibilities.

**Comment by pvi-github** [comment]
Great news thanks... i"ll give it a try then :)

(If you need a review or feedback once your v1.15 version is out you'll just need to ask)

**Comment by pvi-github** [comment]
Hello @philbertphotos I started a osTicket branch there : [https://github.com/pvi-github/osTicket/tree/bootstrap_template_for_1.15.x](https://github.com/pvi-github/osTicket/tree/bootstrap_template_for_1.15.x)

The patched version of osTicket i've made isolates the view (html, css, js) from the rest with the help of Twig templating engine.

You can now switch to your template with a define('THEME', "bootstrap'); in the ost-config.php file

There is also a default theme named 'legacy' which produces  the same output as the current osTicket efault user interface.

Currently it's a work in progress because I only did it as a proof of concept for the index.php home page.

it seems to be working as expected but till the other pages are switched to Twig it cannot be used in production of course.

What do you think of this ?

**Comment by philbertphotos** [comment]
I would implement it in if it can be stabilized ... sounds REAL cool.

**Comment by philbertphotos** [comment]
May be a theme engine that can be easily integrated to osticket

**Comment by pvi-github** [comment]
Yes maybe... I'd be happy of that.
Though there is a big question to ask because I do not know osTicket community very well -> would they accept such proposal because it would be huge patch to review ?

**Comment by philbertphotos** [comment]
1.15 Ready
