### ISSUE TITLE
Bug report: Message won't be saved

### ISSUE THREAD

**Issue by djzwerg** [philbertphotos/osticket-bootstrap-theme#28]
While creating a ticket the message field would not be saved (v1.14).

**Comment by djzwerg** [comment]
The issue still occurs at v1.15.

**Comment by djzwerg** [comment]
Note: If you're going to create a ticket via scp the body contains the information. But as a guest the message body is still empty.

**Comment by djzwerg** [comment]
After a few tests I think the file \upload\open.php occurs this issue.

**Comment by philbertphotos** [comment]
I will look at this and see if I can find the issue.

**Comment by mrkylegp** [comment]
This broke my v1.15 and users could not reply to tickets from the client side. Just kept giving an error stating "Correct any errors below and try again." but there was no errors. Had to revert back to the stock client views.

**Comment by philbertphotos** [comment]
Finally installed 1.5.1 so I am working on it.

**Comment by mrkylegp** [comment]
> Finally installed 1.5.1 so I am working on it.

Awesome, thankyou!
v1.15.3.1 just released too.

**Comment by djzwerg** [comment]
Maybe we can close this issue?

**Comment by mrkylegp** [comment]
> Maybe we can close this issue?

Why? Has there been any update to support v.15.x?

If so, this issue is still current.

**Comment by djzwerg** [comment]
Because this issue should be solved with https://github.com/philbertphotos/osticket-bootstrap-theme/commit/30850c8e25978b9bd3f9ef1c966dc6303676e29c

The v15.x should be another one I think. 

As described at my PR the issue is gone after the few code changes.

**Comment by fernandogiacomino** [comment]
Hi Joseph Philbert,Thank you for getting in touch with us. We have received your message and will be responding to your enquiry as soon as possible.-------------------------------------------------------------Date: 2021-07-28-------------------------------------------------------------Name: Joseph PhilbertEmail: ***@***.***: Sistemas-------------------------------------------------------------Finally installed 1.5.1 so I am working on it.-- You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub:https://github.com/philbertphotos/osticket-bootstrap-theme/issues/28#issuecomment-888003516Powered by LiveZilla Live Help [https://www.livezilla.net/]Ticket History:https://clientes.dertienda.ar/ticket.php?id=11704&hash=E6D994D84798&salt=f36cea7d6b596a33def6782cc96641af[E6D994D84798]

**Comment by philbertphotos** [comment]
Closed updated for  v.15.x
